"""CloudFormation YAML generator: structured architecture -> template."""
from __future__ import annotations

import yaml

from .plan import Plan, pascal, sg_desc


def ref(n):
    return {"Ref": n}


def att(n, a):
    return {"Fn::GetAtt": [n, a]}


def sub(s):
    return {"Fn::Sub": s}


class _Dumper(yaml.SafeDumper):
    def ignore_aliases(self, data):
        return True


def _str_repr(dumper, data):
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


_Dumper.add_representer(str, _str_repr)


def dump_yaml(obj: dict) -> str:
    return yaml.dump(obj, Dumper=_Dumper, sort_keys=False, default_flow_style=False, width=110, allow_unicode=False)


LAMBDA_CODE = """import json


def handler(event, context):
    # Placeholder generated by Syntax AI - replace with your application code.
    print(json.dumps(event))
    return {"statusCode": 200, "body": "ok"}
"""

WEB_USER_DATA = """#!/bin/bash
# Placeholder web server so the load balancer health check passes. Replace with your application.
dnf install -y nginx
systemctl enable --now nginx
"""


def build(plan: Plan) -> dict:
    p = plan
    R: dict[str, dict] = {}
    names: dict[str, str] = {}
    suffix = {"alb": "Alb", "ec2": "Instance", "rds": "Db", "s3": "Bucket", "lambda": "Function",
              "dynamodb": "Table", "sqs": "Queue", "sns": "Topic"}
    for s in p.services:
        names[s["id"]] = pascal(s["id"]) + suffix[s["type"]]

    def tags(name, comp=None):
        t = [{"Key": "Name", "Value": sub("${NamePrefix}-" + name)}, {"Key": "Environment", "Value": ref("Environment")}]
        if comp:
            t.append({"Key": "syntax-ai:component", "Value": comp})
        return t

    def meta(comp):
        return {"SyntaxAI": {"Component": comp}}

    params: dict = {
        "Environment": {"Type": "String", "Default": p.env, "AllowedValues": ["development", "staging", "production"],
                        "Description": "Deployment environment"},
        "NamePrefix": {"Type": "String", "Default": p.prefix, "Description": "Prefix used in resource Name tags"},
    }
    if p.has_vpc:
        params["VpcCidr"] = {"Type": "String", "Default": p.cidr,
                             "AllowedPattern": r"^(\d{1,3}\.){3}\d{1,3}/(1[6-9]|20)$",
                             "Description": "VPC CIDR block (/16 to /20)"}
    if p.by_type["ec2"]:
        params["LatestAmiId"] = {"Type": "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>",
                                 "Default": "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64",
                                 "Description": "Amazon Linux 2023 AMI resolved from SSM"}
    if p.https:
        params["CertificateArn"] = {"Type": "String", "Description": "ARN of an ACM certificate in this region for the HTTPS listener",
                                    "AllowedPattern": "^arn:aws[a-z-]*:acm:.+"}

    retain = "Retain" if p.prod else "Delete"

    # ------------------------------------------------------------ network
    pub, priv = [], []
    if p.has_vpc:
        R["Vpc"] = {"Type": "AWS::EC2::VPC", "Properties": {"CidrBlock": ref("VpcCidr"), "EnableDnsSupport": True,
                                                            "EnableDnsHostnames": True, "Tags": tags("vpc")}}
        if p.needs_public:
            R["InternetGateway"] = {"Type": "AWS::EC2::InternetGateway", "Properties": {"Tags": tags("igw")}}
            R["VpcGatewayAttachment"] = {"Type": "AWS::EC2::VPCGatewayAttachment",
                                         "Properties": {"VpcId": ref("Vpc"), "InternetGatewayId": ref("InternetGateway")}}
            R["PublicRouteTable"] = {"Type": "AWS::EC2::RouteTable", "Properties": {"VpcId": ref("Vpc"), "Tags": tags("public-rt")}}
            R["PublicRoute"] = {"Type": "AWS::EC2::Route", "DependsOn": "VpcGatewayAttachment",
                                "Properties": {"RouteTableId": ref("PublicRouteTable"), "DestinationCidrBlock": "0.0.0.0/0",
                                               "GatewayId": ref("InternetGateway")}}
        for i in range(p.az_count):
            az = {"Fn::Select": [i, {"Fn::GetAZs": ""}]}
            if p.needs_public:
                n = f"PublicSubnet{i + 1}"
                R[n] = {"Type": "AWS::EC2::Subnet", "Properties": {
                    "VpcId": ref("Vpc"), "AvailabilityZone": az, "MapPublicIpOnLaunch": True,
                    "CidrBlock": {"Fn::Select": [i, {"Fn::Cidr": [ref("VpcCidr"), 6, 8]}]}, "Tags": tags(f"public-{i + 1}")}}
                R[f"PublicSubnetRouteTableAssociation{i + 1}"] = {"Type": "AWS::EC2::SubnetRouteTableAssociation", "Properties": {
                    "SubnetId": ref(n), "RouteTableId": ref("PublicRouteTable")}}
                pub.append(n)
            if p.needs_private:
                n = f"PrivateSubnet{i + 1}"
                R[n] = {"Type": "AWS::EC2::Subnet", "Properties": {
                    "VpcId": ref("Vpc"), "AvailabilityZone": az, "MapPublicIpOnLaunch": False,
                    "CidrBlock": {"Fn::Select": [3 + i, {"Fn::Cidr": [ref("VpcCidr"), 6, 8]}]}, "Tags": tags(f"private-{i + 1}")}}
                priv.append(n)
        for i in range(p.nat_count):
            R[f"NatEip{i + 1}"] = {"Type": "AWS::EC2::EIP", "DependsOn": "VpcGatewayAttachment",
                                   "Properties": {"Domain": "vpc", "Tags": tags(f"nat-eip-{i + 1}")}}
            R[f"NatGateway{i + 1}"] = {"Type": "AWS::EC2::NatGateway", "Properties": {
                "AllocationId": att(f"NatEip{i + 1}", "AllocationId"), "SubnetId": ref(pub[i]), "Tags": tags(f"nat-{i + 1}")}}
        for i, sn in enumerate(priv):
            R[f"PrivateRouteTable{i + 1}"] = {"Type": "AWS::EC2::RouteTable", "Properties": {"VpcId": ref("Vpc"), "Tags": tags(f"private-rt-{i + 1}")}}
            if p.nat_count:
                R[f"PrivateRoute{i + 1}"] = {"Type": "AWS::EC2::Route", "Properties": {
                    "RouteTableId": ref(f"PrivateRouteTable{i + 1}"), "DestinationCidrBlock": "0.0.0.0/0",
                    "NatGatewayId": ref(f"NatGateway{min(i, p.nat_count - 1) + 1}")}}
            R[f"PrivateSubnetRouteTableAssociation{i + 1}"] = {"Type": "AWS::EC2::SubnetRouteTableAssociation", "Properties": {
                "SubnetId": ref(sn), "RouteTableId": ref(f"PrivateRouteTable{i + 1}")}}

    def subnet_for(idx: int, tier: str) -> str:
        pool = pub if tier == "public" else priv
        return pool[idx % len(pool)]

    # ------------------------------------------------------------ security groups
    sg: dict[str, str] = {}
    for s in p.services:
        if p.tier[s["id"]] is None:
            continue
        n = pascal(s["id"]) + "Sg"
        sg[s["id"]] = n
        props = {"GroupDescription": sg_desc(s["label"]), "VpcId": ref("Vpc"),
                 "Tags": tags(f"{s['id']}-sg", s["id"])}
        if s["type"] == "alb":
            rules = [{"IpProtocol": "tcp", "FromPort": 80, "ToPort": 80, "CidrIp": "0.0.0.0/0", "Description": "HTTP from the internet"}]
            if p.https:
                rules.append({"IpProtocol": "tcp", "FromPort": 443, "ToPort": 443, "CidrIp": "0.0.0.0/0", "Description": "HTTPS from the internet"})
            props["SecurityGroupIngress"] = rules
        R[n] = {"Type": "AWS::EC2::SecurityGroup", "Properties": props}
    k = 0
    for a, b in p.conns():
        if a["id"] in sg and b["id"] in sg:
            port = None
            if a["type"] == "alb" and b["type"] == "ec2":
                port = 80
            elif a["type"] in ("ec2", "lambda") and b["type"] == "rds":
                port = p.db_port(b)
            if port:
                k += 1
                R[f"Ingress{pascal(a['id'])}To{pascal(b['id'])}"] = {"Type": "AWS::EC2::SecurityGroupIngress", "Properties": {
                    "GroupId": ref(sg[b["id"]]), "IpProtocol": "tcp", "FromPort": port, "ToPort": port,
                    "SourceSecurityGroupId": ref(sg[a["id"]]), "Description": f"{a['id']} to {b['id']} on {port}"}}

    # ------------------------------------------------------------ data services
    for s in p.by_type["s3"]:
        n = names[s["id"]]
        R[n] = {"Type": "AWS::S3::Bucket", "DeletionPolicy": retain, "UpdateReplacePolicy": retain, "Metadata": meta(s["id"]),
                "Properties": {
                    "BucketEncryption": {"ServerSideEncryptionConfiguration": [{"ServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}]},
                    "PublicAccessBlockConfiguration": {"BlockPublicAcls": True, "BlockPublicPolicy": True,
                                                       "IgnorePublicAcls": True, "RestrictPublicBuckets": True},
                    "OwnershipControls": {"Rules": [{"ObjectOwnership": "BucketOwnerEnforced"}]},
                    "Tags": tags(s["id"], s["id"])}}
        if p.backups or p.prod:
            R[n]["Properties"]["VersioningConfiguration"] = {"Status": "Enabled"}
        R[n + "Policy"] = {"Type": "AWS::S3::BucketPolicy", "Properties": {"Bucket": ref(n), "PolicyDocument": {
            "Version": "2012-10-17", "Statement": [{
                "Sid": "DenyInsecureTransport", "Effect": "Deny", "Principal": "*", "Action": "s3:*",
                "Resource": [att(n, "Arn"), sub("${" + n + ".Arn}/*")],
                "Condition": {"Bool": {"aws:SecureTransport": "false"}}}]}}}

    for s in p.by_type["dynamodb"]:
        R[names[s["id"]]] = {"Type": "AWS::DynamoDB::Table", "DeletionPolicy": retain, "UpdateReplacePolicy": retain,
                             "Metadata": meta(s["id"]), "Properties": {
            "BillingMode": "PAY_PER_REQUEST",
            "AttributeDefinitions": [{"AttributeName": "pk", "AttributeType": "S"}],
            "KeySchema": [{"AttributeName": "pk", "KeyType": "HASH"}],
            "SSESpecification": {"SSEEnabled": True},
            "PointInTimeRecoverySpecification": {"PointInTimeRecoveryEnabled": bool(p.backups or p.prod)},
            "DeletionProtectionEnabled": p.prod, "Tags": tags(s["id"], s["id"])}}

    for s in p.by_type["sqs"]:
        n = names[s["id"]]
        R[n] = {"Type": "AWS::SQS::Queue", "Metadata": meta(s["id"]),
                "Properties": {"SqsManagedSseEnabled": True, "VisibilityTimeout": 180, "Tags": tags(s["id"], s["id"])}}
        R[n + "Policy"] = {"Type": "AWS::SQS::QueuePolicy", "Properties": {"Queues": [ref(n)], "PolicyDocument": {
            "Version": "2012-10-17", "Statement": [{
                "Sid": "DenyInsecureTransport", "Effect": "Deny", "Principal": "*", "Action": "sqs:*",
                "Resource": att(n, "Arn"), "Condition": {"Bool": {"aws:SecureTransport": "false"}}}]}}}

    for s in p.by_type["sns"]:
        R[names[s["id"]]] = {"Type": "AWS::SNS::Topic", "Metadata": meta(s["id"]),
                             "Properties": {"KmsMasterKeyId": "alias/aws/sns", "Tags": tags(s["id"], s["id"])}}

    for kind, tier in (("Private", "private"), ("Public", "public")):
        if any(p.tier[s["id"]] == tier for s in p.by_type["rds"]):
            R[f"DbSubnetGroup{kind}"] = {"Type": "AWS::RDS::DBSubnetGroup", "Properties": {
                "DBSubnetGroupDescription": f"{kind} subnets for RDS", "SubnetIds": [ref(x) for x in (priv if tier == "private" else pub)],
                "Tags": tags(f"db-subnets-{tier}")}}
    for s in p.by_type["rds"]:
        n = names[s["id"]]
        engine = p.db_engine(s)
        tier = p.tier[s["id"]]
        props = {
            "Engine": engine, "DBInstanceClass": f"db.t3.{p.size}", "AllocatedStorage": "20", "StorageType": "gp3",
            "StorageEncrypted": True, "MultiAZ": p.rds_multi_az(s), "BackupRetentionPeriod": p.rds_backup_days(s),
            "DeletionProtection": p.prod, "PubliclyAccessible": tier == "public",
            "MasterUsername": "dbadmin", "ManageMasterUserPassword": True,
            "DBSubnetGroupName": ref("DbSubnetGroupPublic" if tier == "public" else "DbSubnetGroupPrivate"),
            "VPCSecurityGroups": [ref(sg[s["id"]])], "AutoMinorVersionUpgrade": True, "CopyTagsToSnapshot": True,
            "Tags": tags(s["id"], s["id"])}
        if p.logging:
            props["EnableCloudwatchLogsExports"] = ["postgresql", "upgrade"] if engine == "postgres" else ["error", "general", "slowquery"]
        pol = "Snapshot" if p.prod else "Delete"
        R[n] = {"Type": "AWS::RDS::DBInstance", "DeletionPolicy": pol, "UpdateReplacePolicy": pol, "Metadata": meta(s["id"]), "Properties": props}

    # ------------------------------------------------------------ IAM + compute
    def statements(comp):
        st = []
        for a, b in p.conns():
            if a["id"] == comp["id"] and a["type"] in ("ec2", "lambda"):
                bn = names[b["id"]]
                if b["type"] == "s3":
                    st.append({"Effect": "Allow", "Action": ["s3:GetObject", "s3:PutObject"], "Resource": sub("${" + bn + ".Arn}/*")})
                    st.append({"Effect": "Allow", "Action": "s3:ListBucket", "Resource": att(bn, "Arn")})
                elif b["type"] == "dynamodb":
                    st.append({"Effect": "Allow", "Action": ["dynamodb:GetItem", "dynamodb:PutItem", "dynamodb:UpdateItem",
                                                              "dynamodb:DeleteItem", "dynamodb:Query"], "Resource": att(bn, "Arn")})
                elif b["type"] == "sqs":
                    st.append({"Effect": "Allow", "Action": ["sqs:SendMessage", "sqs:ReceiveMessage", "sqs:DeleteMessage", "sqs:GetQueueAttributes"],
                               "Resource": att(bn, "Arn")})
                elif b["type"] == "sns":
                    st.append({"Effect": "Allow", "Action": "sns:Publish", "Resource": ref(bn)})
                elif b["type"] == "rds":
                    st.append({"Effect": "Allow", "Action": "secretsmanager:GetSecretValue", "Resource": att(bn, "MasterUserSecret.SecretArn")})
                elif b["type"] == "lambda":
                    st.append({"Effect": "Allow", "Action": "lambda:InvokeFunction", "Resource": att(bn, "Arn")})
            if b["id"] == comp["id"] and comp["type"] == "lambda" and a["type"] == "sqs":
                st.append({"Effect": "Allow", "Action": ["sqs:ReceiveMessage", "sqs:DeleteMessage", "sqs:GetQueueAttributes"],
                           "Resource": att(names[a["id"]], "Arn")})
        return st

    def role(comp, service, managed):
        n = pascal(comp["id"]) + "Role"
        props = {"AssumeRolePolicyDocument": {"Version": "2012-10-17", "Statement": [{
            "Effect": "Allow", "Principal": {"Service": service}, "Action": "sts:AssumeRole"}]},
            "ManagedPolicyArns": managed, "Tags": tags(f"{comp['id']}-role", comp["id"])}
        st = statements(comp)
        if st:
            props["Policies"] = [{"PolicyName": "least-privilege-access", "PolicyDocument": {"Version": "2012-10-17", "Statement": st}}]
        R[n] = {"Type": "AWS::IAM::Role", "Properties": props}
        return n

    targeted = {t["id"] for alb in p.by_type["alb"] for t in p.alb_targets(alb)}
    for idx, s in enumerate(p.by_type["ec2"]):
        rn = role(s, "ec2.amazonaws.com", [sub("arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore")])
        R[pascal(s["id"]) + "InstanceProfile"] = {"Type": "AWS::IAM::InstanceProfile", "Properties": {"Roles": [ref(rn)]}}
        props = {
            "ImageId": ref("LatestAmiId"), "InstanceType": f"t3.{p.size}", "SubnetId": ref(subnet_for(idx, p.tier[s["id"]])),
            "SecurityGroupIds": [ref(sg[s["id"]])], "IamInstanceProfile": ref(pascal(s["id"]) + "InstanceProfile"),
            "Monitoring": p.monitoring, "MetadataOptions": {"HttpTokens": "required", "HttpEndpoint": "enabled"},
            "BlockDeviceMappings": [{"DeviceName": "/dev/xvda", "Ebs": {"VolumeSize": 20, "VolumeType": "gp3", "Encrypted": True,
                                                                        "DeleteOnTermination": True}}],
            "Tags": tags(s["id"], s["id"])}
        if s["id"] in targeted:
            props["UserData"] = {"Fn::Base64": WEB_USER_DATA}
        R[names[s["id"]]] = {"Type": "AWS::EC2::Instance", "Metadata": meta(s["id"]), "Properties": props}

    for s in p.by_type["lambda"]:
        in_vpc = p.tier[s["id"]] == "private"
        managed = [sub("arn:${AWS::Partition}:iam::aws:policy/service-role/" +
                       ("AWSLambdaVPCAccessExecutionRole" if in_vpc else "AWSLambdaBasicExecutionRole"))]
        rn = role(s, "lambda.amazonaws.com", managed)
        env = {}
        for a, b in p.conns():
            if a["id"] == s["id"]:
                key, bn = b["id"].upper(), names[b["id"]]
                if b["type"] == "s3":
                    env[f"S3_BUCKET_{key}"] = ref(bn)
                elif b["type"] == "dynamodb":
                    env[f"DYNAMODB_TABLE_{key}"] = ref(bn)
                elif b["type"] == "sqs":
                    env[f"SQS_QUEUE_URL_{key}"] = ref(bn)
                elif b["type"] == "sns":
                    env[f"SNS_TOPIC_ARN_{key}"] = ref(bn)
                elif b["type"] == "rds":
                    env[f"DB_HOST_{key}"] = att(bn, "Endpoint.Address")
                    env[f"DB_PORT_{key}"] = att(bn, "Endpoint.Port")
                    env[f"DB_SECRET_ARN_{key}"] = att(bn, "MasterUserSecret.SecretArn")
        props = {"Runtime": "python3.12", "Handler": "index.handler", "Role": att(rn, "Arn"), "Timeout": 30, "MemorySize": 256,
                 "Code": {"ZipFile": LAMBDA_CODE}, "Tags": tags(s["id"], s["id"])}
        if env:
            props["Environment"] = {"Variables": env}
        if in_vpc:
            props["VpcConfig"] = {"SubnetIds": [ref(x) for x in priv], "SecurityGroupIds": [ref(sg[s["id"]])]}
        R[names[s["id"]]] = {"Type": "AWS::Lambda::Function", "Metadata": meta(s["id"]), "Properties": props}
    for a, b in p.conns():
        if b["type"] == "lambda" and a["type"] == "sqs":
            R[f"{pascal(a['id'])}To{pascal(b['id'])}Mapping"] = {"Type": "AWS::Lambda::EventSourceMapping", "Properties": {
                "FunctionName": ref(names[b["id"]]), "EventSourceArn": att(names[a["id"]], "Arn"), "BatchSize": 10}}
        elif b["type"] == "lambda" and a["type"] == "sns":
            R[f"{pascal(a['id'])}To{pascal(b['id'])}Subscription"] = {"Type": "AWS::SNS::Subscription", "Properties": {
                "TopicArn": ref(names[a["id"]]), "Protocol": "lambda", "Endpoint": att(names[b["id"]], "Arn")}}
            R[f"{pascal(a['id'])}To{pascal(b['id'])}Permission"] = {"Type": "AWS::Lambda::Permission", "Properties": {
                "FunctionName": ref(names[b["id"]]), "Action": "lambda:InvokeFunction", "Principal": "sns.amazonaws.com",
                "SourceArn": ref(names[a["id"]])}}

    # ------------------------------------------------------------ load balancers
    for s in p.by_type["alb"]:
        n = names[s["id"]]
        L = pascal(s["id"])
        R[n] = {"Type": "AWS::ElasticLoadBalancingV2::LoadBalancer", "DependsOn": "VpcGatewayAttachment", "Metadata": meta(s["id"]),
                "Properties": {"Type": "application", "Scheme": "internet-facing", "SecurityGroups": [ref(sg[s["id"]])],
                               "Subnets": [ref(x) for x in pub],
                               "LoadBalancerAttributes": [
                                   {"Key": "routing.http.drop_invalid_header_fields.enabled", "Value": "true"},
                                   {"Key": "deletion_protection.enabled", "Value": "true" if p.prod else "false"}],
                               "Tags": tags(s["id"], s["id"])}}
        targets = p.alb_targets(s)
        if targets:
            R[L + "TargetGroup"] = {"Type": "AWS::ElasticLoadBalancingV2::TargetGroup", "Properties": {
                "Port": 80, "Protocol": "HTTP", "VpcId": ref("Vpc"), "TargetType": "instance",
                "Targets": [{"Id": ref(names[t["id"]]), "Port": 80} for t in targets],
                "HealthCheckPath": "/", "HealthCheckProtocol": "HTTP", "Tags": tags(f"{s['id']}-tg")}}
            forward = [{"Type": "forward", "TargetGroupArn": ref(L + "TargetGroup")}]
        else:
            forward = [{"Type": "fixed-response", "FixedResponseConfig": {"StatusCode": "503", "ContentType": "text/plain",
                                                                          "MessageBody": "No targets configured"}}]
        if p.https:
            R[L + "HttpListener"] = {"Type": "AWS::ElasticLoadBalancingV2::Listener", "Properties": {
                "LoadBalancerArn": ref(n), "Port": 80, "Protocol": "HTTP", "DefaultActions": [{
                    "Type": "redirect", "RedirectConfig": {"Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}]}}
            R[L + "HttpsListener"] = {"Type": "AWS::ElasticLoadBalancingV2::Listener", "Properties": {
                "LoadBalancerArn": ref(n), "Port": 443, "Protocol": "HTTPS", "SslPolicy": "ELBSecurityPolicy-TLS13-1-2-2021-06",
                "Certificates": [{"CertificateArn": ref("CertificateArn")}], "DefaultActions": forward}}
        else:
            R[L + "HttpListener"] = {"Type": "AWS::ElasticLoadBalancingV2::Listener", "Properties": {
                "LoadBalancerArn": ref(n), "Port": 80, "Protocol": "HTTP", "DefaultActions": forward}}

    # ------------------------------------------------------------ logging + monitoring
    if p.logging and p.has_vpc:
        R["FlowLogGroup"] = {"Type": "AWS::Logs::LogGroup", "Properties": {"RetentionInDays": 90 if p.prod else 30}}
        R["FlowLogRole"] = {"Type": "AWS::IAM::Role", "Properties": {
            "AssumeRolePolicyDocument": {"Version": "2012-10-17", "Statement": [{
                "Effect": "Allow", "Principal": {"Service": "vpc-flow-logs.amazonaws.com"}, "Action": "sts:AssumeRole"}]},
            "Policies": [{"PolicyName": "flow-log-delivery", "PolicyDocument": {"Version": "2012-10-17", "Statement": [{
                "Effect": "Allow", "Action": ["logs:CreateLogStream", "logs:PutLogEvents", "logs:DescribeLogStreams"],
                "Resource": [att("FlowLogGroup", "Arn"), sub("${FlowLogGroup.Arn}:*")]}]}}]}}
        R["VpcFlowLog"] = {"Type": "AWS::EC2::FlowLog", "Properties": {
            "ResourceType": "VPC", "ResourceId": ref("Vpc"), "TrafficType": "ALL", "LogDestinationType": "cloud-watch-logs",
            "LogGroupName": ref("FlowLogGroup"), "DeliverLogsPermissionArn": att("FlowLogRole", "Arn")}}

    if p.monitoring:
        alarms = []
        for s in p.by_type["ec2"]:
            alarms.append((f"{pascal(s['id'])}CpuAlarm", "AWS/EC2", "CPUUtilization", [{"Name": "InstanceId", "Value": ref(names[s['id']])}],
                           "Average", 80, "CPU above 80%"))
        for s in p.by_type["rds"]:
            alarms.append((f"{pascal(s['id'])}CpuAlarm", "AWS/RDS", "CPUUtilization",
                           [{"Name": "DBInstanceIdentifier", "Value": ref(names[s['id']])}], "Average", 80, "CPU above 80%"))
        for s in p.by_type["alb"]:
            alarms.append((f"{pascal(s['id'])}Elb5xxAlarm", "AWS/ApplicationELB", "HTTPCode_ELB_5XX_Count",
                           [{"Name": "LoadBalancer", "Value": att(names[s['id']], "LoadBalancerFullName")}], "Sum", 10, "More than 10 ELB 5XX in 5 minutes"))
        if alarms:
            R["AlarmTopic"] = {"Type": "AWS::SNS::Topic", "Properties": {"DisplayName": "Syntax AI alarms"}}
            for n, ns, metric, dims, stat, thr, desc in alarms:
                R[n] = {"Type": "AWS::CloudWatch::Alarm", "Properties": {
                    "AlarmDescription": desc, "Namespace": ns, "MetricName": metric, "Dimensions": dims, "Statistic": stat,
                    "Period": 300, "EvaluationPeriods": 2, "Threshold": thr, "ComparisonOperator": "GreaterThanThreshold",
                    "TreatMissingData": "notBreaching", "AlarmActions": [ref("AlarmTopic")]}}

    # ------------------------------------------------------------ outputs
    out: dict = {}
    if p.has_vpc:
        out["VpcId"] = {"Value": ref("Vpc")}
    for s in p.services:
        n, L = names[s["id"]], pascal(s["id"])
        if s["type"] == "alb":
            out[f"{L}DnsName"] = {"Description": "Load balancer DNS name", "Value": att(n, "DNSName")}
        elif s["type"] == "rds":
            out[f"{L}Endpoint"] = {"Description": "Database endpoint", "Value": att(n, "Endpoint.Address")}
            out[f"{L}SecretArn"] = {"Description": "Secrets Manager secret holding the master password", "Value": att(n, "MasterUserSecret.SecretArn")}
        elif s["type"] in ("s3", "dynamodb", "sqs", "sns", "ec2", "lambda"):
            out[f"{L}{'Name' if s['type'] in ('s3', 'dynamodb', 'lambda') else 'Ref'}"] = {"Value": ref(n)}
    if "AlarmTopic" in R:
        out["AlarmTopicArn"] = {"Description": "Subscribe your email/pager to this topic", "Value": ref("AlarmTopic")}

    template = {"AWSTemplateFormatVersion": "2010-09-09",
                "Description": f"Syntax AI generated stack ({p.env}) - {len(p.services)} components",
                "Parameters": params, "Resources": R}
    if out:
        template["Outputs"] = out
    return template


def generate(plan: Plan) -> str:
    header = ("# Generated by Syntax AI from a validated architecture.\n"
              f"# Environment: {plan.env} | Region: {plan.region}\n")
    return header + dump_yaml(build(plan))
